#!/usr/bin/env bash

./seleccion 1 ciudades.txt rutas.txt
./seleccion 2 ciudades.txt rutas.txt

./division ciudades.txt rutas.txt seleccion1.txt seleccion2.txt

ronda=0
maxima_ronda=50

while [[ ${ronda} -lt ${maxima_ronda} ]]
do
    ./recolectar 1 ciudades.txt rutas.txt imperio1.txt
    ./recolectar 2 ciudades.txt rutas.txt imperio2.txt

    ./producir 1 ciudades.txt rutas.txt imperio1.txt cosecha1.txt imperio2.txt cosecha2.txt
    ./producir 2 ciudades.txt rutas.txt imperio1.txt cosecha1.txt imperio2.txt cosecha2.txt

    mv ./imperio1_temp.txt imperio1.txt
    mv ./imperio2_temp.txt imperio2.txt
    mv ./harvest1_temp.txt cosecha1.txt
    mv ./harvest2_temp.txt cosecha2.txt

    ./tactica 1 ciudades.txt rutas.txt imperio1.txt cosecha1.txt imperio2.txt cosecha2.txt
    ./tactica 2 ciudades.txt rutas.txt imperio1.txt cosecha1.txt imperio2.txt cosecha2.txt

    ./contienda ciudades.txt rutas.txt imperio1.txt imperio2.txt ataque1.txt ataque2.txt

    ./ganador ${ronda} ciudades.txt rutas.txt imperio1.txt cosecha1.txt imperio2.txt cosecha2.txt
    if [[ -s ./ganador.txt ]]
    then
        exit 0
    fi

    ronda=$((ronda+1))
done