#!/usr/bin/env bash

./seleccion 1 ciudades.txt rutas.txt
./seleccion 2 ciudades.txt rutas.txt

./division ciudades.txt rutas.txt seleccion1.txt seleccion2.txt

ronda=1
maxima_ronda=11

while [[ ${ronda} -lt ${maxima_ronda} ]]
do
    echo round: ${ronda}
    ./recolectar 1 ciudades.txt rutas.txt imperio1.txt
    ./recolectar 2 ciudades.txt rutas.txt imperio2.txt

    ./producir 1 ciudades.txt rutas.txt imperio1.txt cosecha1.txt imperio2.txt cosecha2.txt
    ./producir 2 ciudades.txt rutas.txt imperio1.txt cosecha1.txt imperio2.txt cosecha2.txt

    python3 post_producir.py

    ./tactica 1 ciudades.txt rutas.txt imperio1.txt cosecha1.txt imperio2.txt cosecha2.txt
    ./tactica 2 ciudades.txt rutas.txt imperio1.txt cosecha1.txt imperio2.txt cosecha2.txt

    ./contienda ciudades.txt rutas.txt imperio1.txt imperio2.txt ataque1.txt ataque2.txt

    ./ganador ${ronda} ciudades.txt rutas.txt imperio1.txt cosecha1.txt imperio2.txt cosecha2.txt
    if [[ -f ./ganador.txt ]]
    then
	echo "The winner is:"
	cat ./ganador.txt
        exit 0
    fi

    ronda=$((ronda+1))
done
